[package]
name = "position-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
uom = { workspace = true }
linalg = { path = "../linalg" }
heapless = { workspace = true }
rand = { version = "0.10.1", default-features = false }
rand_distr = { version = "0.6.0", default-features = false }

[dev-dependencies]
approx = { version = "0.5.1", default-features = false }
